package visMan;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;

import java.io.File;

import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.TextArea;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;

public class NewUserController {
	@FXML
	private TextField nameField;
	@FXML
	private ToggleGroup gender;
	@FXML
	private TextField contactField;
	@FXML
	private TextArea addressField;
	@FXML
	private ToggleGroup category;
	@FXML
	private TextField purposeField;
	@FXML
	private ImageView userImage;
	@FXML
	private Button captureButton;
	@FXML
	private Button reviewButton;
	@FXML
	private Button cancelButton;

	// Event Listener on Button[#captureButton].onAction
	@FXML
	public void openCaptureWindow(ActionEvent event) throws Exception {
		{
        FXMLLoader loader = new FXMLLoader(getClass().getResource("WebCamCapture.fxml"));
        Parent webCamRoot = (Parent) loader.load();
        Scene newUser = new Scene(webCamRoot,400,600);
        WebCamCaptureController controller = (WebCamCaptureController) loader.getController();
//        control.initData(selectedSong);
        Stage stager = new Stage();
        stager.setScene(newUser);
        stager.setResizable(false);
        stager.setTitle("Checkin New User");
        stager.setOnHiding(new EventHandler<WindowEvent>() {

            @Override
            public void handle(WindowEvent event) {
                Platform.runLater(new Runnable() {

                    @Override
                    public void run() {
                        stager.close();
                    }
                });
            }
        });
        stager.showAndWait();
		}
		
        File file = new File("temp.png");
        Image image = new Image(file.toURI().toString());
		userImage.setImage(image);
		
	}
	// Event Listener on Button[#reviewButton].onAction
	@FXML
	public void reviewAndPrint(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#cancelButton].onAction
	@FXML
	public void cancelExecute(ActionEvent event) {
		// TODO Autogenerated
	}
}
